boke/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'boke'
urlpatterns = [
    path('', views.home, name='home'),
    path('^post/<int:pk>/', views.pages, name='pages'),
    path('files/<int:year>/<int:month>/', views.files, name='files'),
    path('classification/<int:pk>/', views.classification, name='classification'),
    path('files/', views.files),
    url(r'^(\d+)$', views.home),
]

comments/urls.py
from django.urls import path

from . import views
app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

my_design/urls.py
from django.urls import path, include
import xadmin

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('', include('boke.urls')),
    path('', include('comments.urls')),
    path('search/', include('haystack.urls')),
]

boke/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    cname = models.CharField(max_length=30)

    def __str__(self):
        return self.cname

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name


class Tag(models.Model):  # 继承models.Model
    tname = models.CharField(max_length=30)

    def __str__(self):
        return self.tname

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Post(models.Model):
    def __str__(self):
        return self.title

    def look_up(self):
        return reverse('boke:pages', kwargs={'pk': self.pk})

    title = models.CharField('标题', max_length=30)
    content = models.TextField('正文')
    excerpt = models.CharField('摘要', max_length=100, blank=True)
    created = models.DateTimeField('创建时间')
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
    # 统计文章阅读量
    views = models.PositiveIntegerField(default=0)

    def statistics(self):  # 统计文章阅读量
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        # 根据时间对文章进行排序
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created']

comments/models.py
from django.db import models
from django.utils import timezone

class Comment(models.Model):
    name = models.CharField('用户名', max_length=50)
    email = models.EmailField('邮箱')
    body = models.TextField('内容')
    created = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('boke.Post', verbose_name='文章', on_delete=models.CASCADE)
    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
    def __str__(self):
        return '{}: {}'.format(self.name, self.body[:20])

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

boke/views.py
from markdown.extensions.toc import TocExtension, slugify
from .models import Post, Category
from django.shortcuts import render, get_object_or_404
import markdown
import re

# 首页 index
from django.core.paginator import Paginator  # 分页


def home(request, i=1):  # 获取全部文章
    num = int(i)
    # 获取所有文章信息（时间）
    lists = Post.objects.all().order_by('-created')
    # 创建分页器
    pj = Paginator(lists, 5)
    # 获取当前页数据
    Pa = pj.page(num)
    return render(request, 'boke/home.html', context={'article_list': Pa})


# 文章详情功能 detail
def pages(request, pk):
    i = get_object_or_404(Post, pk=pk)
    # 文章阅读量
    i.statistics()
    # 自动生成目录
    my = markdown.Markdown(extensions=['markdown.extensions.toc', TocExtension(slugify=slugify)])
    i.content = my.convert(i.content)
    wang = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', my.toc, re.S)
    i.toc = wang.group(1) if wang is not None else ''

    return render(request, 'boke/pages.html', context={'post': i})


# 归档功能 archives
def files(request, year, month):
    # 使用模型管理器filter函数来过滤文章，依据年，月
    lists = Post.objects.filter(created__year=year, created__month=month).order_by('-created')
    return render(request, 'boke/home.html', context={'article_list': lists})


# 分类功能 category
def classification(request, pk):
    dates = get_object_or_404(Category, pk=pk)
    lists = Post.objects.filter(category=dates).order_by('-created')
    return render(request, 'boke/home.html', context={'article_list': lists})

comments/views.py
from boke.models import Post
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from .forms import CommentForm
from django.contrib import messages


@require_POST  # 装饰器
def comment(request, post_pk):
    blog = get_object_or_404(Post, pk=post_pk)
    biaodan = CommentForm(request.POST)
    if biaodan.is_valid():
        pl = biaodan.save(commit=False)
        pl.post = blog
        pl.save()
        messages.add_message(request, messages.SUCCESS,
                             '发表成功！', extra_tags='success')
        return redirect(blog)
    context = {
        'blog': blog,
        'biaodan': biaodan,
    }
    messages.add_message(request, messages.ERROR,
                         '发表失败，请重新填写！！！', extra_tags='danger')
    return render(request, 'comments/display.html', context=context)

templates/base.html
{% load staticfiles %} <!--使用 static 模板标签-->
{% load boke_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>我的博客</title>
        <!-- meta -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- css -->
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="{% static 'boke/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'boke/css/custom.css' %}">
        <!-- js -->
        <script src="{% static 'boke/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'boke/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'boke/js/pace.min.js' %}"></script>
        <script src="{% static 'boke/js/modernizr.custom.js' %}"></script>

        <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

    </head>

<body>
<!--<nav class="navbar navbar-default">-->
<!--    <div class="container-fluid">-->
<!--    <div class="navbar-header">-->
<!--        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">-->
<!--            <span class="sr-only">Toggle navigation</span>-->
<!--            <span class="icon-bar"></span>-->
<!--            <span class="icon-bar"></span>-->
<!--            <span class="icon-bar"></span>-->
<!--        </button>-->
<!--        <a class="navbar-brand" href="#">欢迎光临我的博客</a>-->
<!--    </div>-->
<!--    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">-->
<!--        <ul class="nav navbar-nav">-->
<!--            <li class="active"><a href="{% url 'boke:home' %}">首页 <span class="sr-only"></span></a></li>-->
<!--        </ul>-->
<!--        <form class="navbar-form navbar-left" method="get" action="{% url 'haystack_search' %}">-->
<!--            <div class="form-group">-->
<!--            <input name="q" type="text" class="form-control" placeholder="请输入关键字">-->
<!--            </div>-->
<!--            <button type="submit" class="btn btn-default">搜索</button>-->
<!--        </form>-->
<!--        <ul class="nav navbar-nav navbar-right">-->
<!--            {% if request.session.is_login %}-->
<!--      <li><a href="#">当前在线：{{ request.session.user_name }}</a></li>-->
<!--      <li><a href="/logout/">登出</a></li>-->
<!-- {% else %}-->
<!--      <li><a href="/login/">登录</a></li>-->
<!--      <li><a href="/register/">注册</a></li>-->
<!--{% endif %}-->
<!--        </ul>-->
<!--    </div>-->
<!--    </div>-->
<!--</nav>-->

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">欢迎光临我的博客</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'boke:home' %}">首页 <span class="sr-only"></span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">更 多<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/fenlei/">分类</a></li>
            <li><a href="/guidang/">归档</a></li>
            <li><a href="#">关于</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" method="get" action="{% url 'haystack_search' %}">
        <div class="form-group">
          <input name="q" type="text" class="form-control" placeholder="请输入关键字">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>



{% if messages %}
    {% for tips in messages %}
      <div class="alert alert-{{ tips.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ tips }}
      </div>
    {% endfor %}
{% endif %}
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block my %}
                {% endblock my %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% if post.toc %}
                <div >
                    <h3 class="widget-title">文章目录</h3>
                    <div class="toc">
                        <ul>
                        {{ post.toc|safe }}
                        </ul>
                    </div>
                </div>
                {% endif %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title-1">最新文章</h3>
                    {% get_posts as new_post %}
                    <ul>
                        {% for post in new_post %}
                    <li>
                        <a href="{{ post.look_up }}">{{ post.title }}</a>
                    </li>
                        {% empty %}
                        博主好像什么都没有写！
                        {% endfor %}
                    </ul>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    <a  title="欢迎光临" target="_blank">
                        <hr class="hr-111">python3.7+Django2.2开发的个人博客</a>
                </p>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'boke/js/script.js' %}"></script>

<body>
    <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
    <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
    <script>
        h1js.initHighlightingOnLoad();
        h1js.initLineNumbersOnLoad();
    </script>
</body>
</body>
</html>

templates/boke/fenlei.html
{% load staticfiles %} <!--使用 static 模板标签-->
{% load boke_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>分类界面</title>
</head>
<body>
<div class="widget widget-category">
    <h3 class="widget-title-1">文章分类</h3>
    {% get_classification as type %}
    <ul>
        {% for classification in type %}
        <li><a href="{% url 'boke:classification' classification.pk %}">{{ classification.cname }}</a></li>
        {% endfor %}
    </ul>
    
</div>
</body>
</html>

templates/boke/guidang.html
{% load staticfiles %} <!--使用 static 模板标签-->
{% load boke_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>归档界面</title>
</head>
<body>
<div class="widget widget-archives">
    <h3 class="widget-title-1">随笔归档</h3>
    {% get_files as time %}
    <ul>
        {% for date in time %}
        
        
        <li><a href="{% url 'boke:files' date.year date.month %}">
            {{ date.year }} 年 {{ date.month }} 月</a></li>
        {% endfor %}
    </ul>
</div>
</body>
</html>
<hr>

templates/boke/home.html
{% extends 'base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<body>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block my %}
                {% for post in article_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header" >
                        <h1 class="text-111">
                            <hr class="hr-111">
                          <a href="{{ post.look_up }}">{{ post.title }}</a>
                        </h1>
                        <div class="text-112">
                            <span class="glyphicon glyphicon-time" style="color: rgb(102, 99, 99)"><a href="#"><time class="entry-date" >{{ post.created }}&nbsp;</time></a></span>
                            <span class="glyphicon glyphicon-pencil" style="color: rgb(102, 99, 99)"><a href="#">{{ post.comment_set.count }}&nbsp;</a></span>
                            <span class="glyphicon glyphicon-eye-open" style="color: rgb(102, 99, 99)"><a href="#">{{ post.views }}</a></span>
                        </div>
                        <div class="entry-content">
                          <p>{{ post.excerpt }}</p>
                        </div>
                    </header>
                </article>
                {% empty %}
                <div class="no-post">博主好像什么都没写！</div>
                {% endfor %}
                    <nav aria-label="Page navigation" style="text-align: center;">
                        <ul class="pagination">
                            {% if article_list.has_previous %}
                            <li><a class="extend prev" rel="next" href="{{ article_list.previous_page_number }}">上一页</a></li>
                            {% endif %}
                            {% if article_list.has_next %}
                            <li><a class="extend next" rel="next" href="{{ article_list.next_page_number }}">下一页</a></li>
                            {% endif %}
                        </ul>
                    </nav>
              </ul>
            </nav>
                {% endblock my %}
            </main>
        </div>
    </div>
</div>
</body>
</html>

templates/boke/pages.html
{% extends 'base.html' %}
{% load comments_extras %}
<!DOCTYPE html>
<html>
<body id="single">
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-10">
                {% block my %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span ><a href="#"><time class="entry-date"datetime="{{ post.created }}">发布于：{{ post.created }}&nbsp;</time></a></span>
                            <span ><a href="#">&nbsp;作者：{{ post.author }}&nbsp;</a></span>
                            <span class="post-classification"><a href="#">&nbsp;分类：{{ post.classification.name }}</a></span>
                        </div>
                    </header>
                    <div class="entry-content-1">
                        {{ post.content|safe }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                        {% pinglun_biaodan post %}
                    <div class="comment-list-panel">
                        {% pinglun_ post %}
                    </div>
                </section>
                {% endblock my %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% if post.toc %}
                <div class="mulu-111">
                    <h3 class="widget-title">文章目录</h3>
                <div class="toc">
                    <ul class="mulu-jianju">
                    {{ post.toc|safe }}
                    </ul>
                </div>
                </div>
                {% endif %}
                {% endblock toc %}
            </aside>
        </div>
    </div>
</div>
</body>
</html>

templates/comments/inclusions/cf.html
<form action="{% url 'comments:comment' blog.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
      <div class="col-md-4">
          <label  for="{{ biaodan.name.id_for_label }}">{{ biaodan.name.label }}：</label>
          {{ biaodan.name }}
          {{ biaodan.name.errors }}
      </div>
      <div class="col-md-12">
          <label for="{{ biaodan.email.id_for_label }}">{{ biaodan.email.label }}：</label>
          {{ biaodan.email }}
          {{ biaodan.email.errors }}
      </div>
      <div class="col-md-12">
          <label for="{{ biaodan.body.id_for_label }}">{{ biaodan.body.label }}：</label>
          {{ biaodan.body }}
          {{ biaodan.body.errors }}
      <button type="submit" class="comment-btn">提交</button>
      </div>
  </div>
</form>

templates/comments/inclusions/cl.html
<h3><span>{{ total }}</span> 人参与了评论</h3>
<ul class="comment-list list-unstyled">
    {% for pinglun in liebiao %}
        <li class="comment-item">
            <span class="nickname">用户：{{ pinglun.name }}</span>
            <time class="submit-date">发表于：{{ pinglun.created }}</time>
            <div class="text">
            {{ pinglun.body|linebreaks }}
            </div>
        </li>
    {% empty %}
    暂无评论
    {% endfor %}
</ul>

templates/comments/inclusions/display.html
{% extends 'base.html' %}
{% load comments_extras %}
{% block my %}
  {% pinglun_biaodan post form %}
{% endblock my %}

templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}
{% block my %}
    {% if query %}
        {% for lookup in page.object_list %}
            <article class="post post-{{ lookup.object.pk }}">
                <header class="entry-header">
                    <h1 class="text-111">
                        <hr class="hr-111">
                        <a href="{{ lookup.object.look_up }}">{% highlight lookup.object.title with query %}</a>
                    </h1>
                    <div class="text-112">
                            <span class="glyphicon glyphicon-time" style="color: rgb(102, 99, 99)"><a href="#"><time class="entry-date" >{{ lookup.object.created }}&nbsp;</time></a></span>
                            <span class="glyphicon glyphicon-pencil" style="color: rgb(102, 99, 99)"><a href="#">{{ lookup.object.comment_set.count }}&nbsp;</a></span>
                            <span class="glyphicon glyphicon-eye-open" style="color: rgb(102, 99, 99)"><a href="#">{{ lookup.object.views }}</a></span>
                        </div>
                </header>
            </article>
        {% empty %}
            <div class="no-post">未查询到您想要查询的内容！</div>
        {% endfor %}
        <nav aria-label="Page navigation" style="text-align: center;">
            <ul class="pagination">
                {% if article_list.has_previous %}
                <li><a class="extend prev" rel="next" href="{{ article_list.previous_page_number }}">上一页</a></li>
                {% endif %}
                {% if article_list.has_next %}
                <li><a class="extend next" rel="next" href="{{ article_list.next_page_number }}">下一页</a></li>
                {% endif %}
            </ul>
        </nav>
        {% else %}
            请输入搜索关键字
        {% endif %}
{% endblock my %}